name: SentryX
version: '${project.version}'
main: rod.sentryx.SentryX
api-version: '1.20'

commands:
  gmc:
   description: "Turns you to creative mode! crazy"
  gms:
   description: "Turns you to survival mode! crazy"
  gmsp:
   description: "Turns you to spectator mode! crazy"
  gma:
   description: "Turns you to adventure mode! crazy"
  heal:
   description: "Heals you! crazy"
  feed:
   description: "Feeds you! crazy"
  more:
   description: "Gives you 64 of the current item in your hand! crazy"
  clearchat:
   description: "Clears chat! crazy"
   aliases: [cc]

