name: SentryX
main: rod.sentryx.SentryX
version: 1.0-SNAPSHOT
api-version: 1.20
commands:
  gmc:
    description: Changes game mode to creative
  servergui:
    description: Opens server info GUI
  ping:
    description: Shows your ping
  tps:
    description: Displays TPS
  server:
    description: Server related command
  gms:
    description: Changes game mode to survival
  gma:
    description: Changes game mode to adventure
  gmsp:
    description: Changes game mode to spectator
  heal:
    description: Heals the player
  feed:
    description: Feeds the player
  clearchat:
    description: Clears the chat
  more:
    description: Gives more of the item in hand
  auth:
    description: auth you
  authregister:
    description: register with password
  authreset:
    description: register with password
  stats:
    description: View a player's stats
    usage: /stats <playername>
  resetstats:
    description: Reset a player's stats
    usage: /resetstats <playername>
  infiniteelytra:
    description: Gives you faster + infinte elytra
    usage: /infiniteelytra